### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by kissgabicsabi** [BME-MIT-IET/iet-hf-2022-team-1#3]
This is the issue for unit testing.

**Comment by szabolcs-horvath** [comment]
A könyvtár sorting algoritmusait tesztelem, azok közül is a JavaScript implementációval rendelkezőket.

### Fealdatok

- Megfelelő npm package-ek telepítése és konfigurációja
- Scriptek a tesztek egyszerű futtatására
- Code-coverage mérés
- Lefedettség maximalizálása a tesztelt algoritmusokon
- Felmerülő hibák javítása a könyvtárban
