### ISSUE TITLE
Manual testing

### ISSUE THREAD

**Issue by GTamas015** [BME-MIT-IET/iet-hf-2022-team-1#4]

**Comment by GTamas015** [comment]
This is the issue for exploratory testing.

**Comment by kissgabicsabi** [comment]
Bizonyos algoritmusokat teszteltünk egymás után fűzve. Java nyelv esetén először generáltunk egy random arrayt-t, ezt összekevertük, rendeztük majd kiválasztottuk a legnagyobb/legkisebb elemet. Javascript esetén létrehoztunk egy tömböt, ezt rendeztük és utána kiválasztottunk bizonyos indexű elemeket.

**Comment by badalnoky** [comment]
Nemvolt még meg a pull request elfogadása ezért újranyitottam

**Comment by badalnoky** [comment]
#6
